// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string):Promise<string>;

export function CreateFolder(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetVaultPath():Promise<string>;

export function ListVaultContents():Promise<Array<main.FileInfo>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenVault(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SelectVaultFolder():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
